default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: developer
  password: supersecretpassword
  host: localhost

development:
  <<: *default
  database: hello_world_dev

test:
  <<: *default
  database: hello_world_test

production:
  <<: *default
  database: hello_world_prod